# Generated by Django 6.0.7 on 2026-08-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_types',
            field=models.ManyToManyField(blank=True, to='products.producttype'),
        ),
    ]
